name: Publish

on:
  push:
    tags:
    - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      contents: write
    steps:
      - name: Checkout TIKI SDK Android
        uses: actions/checkout@v3

      - name: Release
        uses: ncipollo/release-action@v1

  docs:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - name: Guide
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/guide --key=${{ secrets.README_API_KEY }}

      - name: Ref
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/ref --key=${{ secrets.README_API_KEY }}
