name: Publish

on:
  push:
    tags:
    - '*.*.*'

jobs:
  publish:
    runs-on: macos-latest
    environment:
      name: Production
    permissions:
      contents: write
    steps:
      - name: Checkout TIKI SDK Android
        uses: actions/checkout@v3
    
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run tests
        run: |
          cd IntegrationTests
          xcodebuild test -project IntegrationTests.xcodeproj -scheme IntegrationTestsRunner -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'

      - name: Release
        uses: ncipollo/release-action@v1

  docs:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - name: Guide
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/guide --key=${{ secrets.README_API_KEY }}

      - name: Ref
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/ref --key=${{ secrets.README_API_KEY }}
